services:
  - type: static
    name: SajalsDietFalsafa
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
    redirects:
      - source: '/*'
        destination: '/index.html'
        status: 200
